---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Ruuvi Greengrass component is a component you can install to AWS GreenGrass device to relay measurements received from your RuuviTags to an MQTT topic and/or IoT Core endpoint."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        'com.hartvi.RuuviTag:pubsub:2':
          policyDescription: Allows access to publish to all topics.
          operations:
            - 'aws.greengrass#PublishToIoTCore'
          resources:
            - '*'
    Message: world
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/ruuvitag-gg-component.zip"
        Unarchive: ZIP
    Lifecycle:
#      Run: "python3 -u {artifacts:decompressedPath}/poll.py {configuration:/Message}"
      Run: "RUUVI_BLE_ADAPTER=Bleson python3 -u {artifacts:decompressedPath}/ruuvitag-gg-component/poll.py {configuration:/Message}"